CREATE TABLE IF NOT EXISTS icd11_sankey_paths (
    sankey_path_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    target_category VARCHAR(160) NOT NULL COMMENT '目标类别',
    substance_category VARCHAR(180) NOT NULL COMMENT '目标物质类别',
    substance_subclass VARCHAR(180) NOT NULL COMMENT '目标物质子类',
    drug_name VARCHAR(300) NOT NULL COMMENT '药物名称',
    indication_original TEXT COMMENT '适应症原文',
    biomarker_name VARCHAR(300) NOT NULL COMMENT '生物标记物名称',
    biomarker_alias VARCHAR(300) COMMENT '英文 biomarker 或别名',
    normalized_indication VARCHAR(300) COMMENT '规范适应症短语',
    disease_entity VARCHAR(300) COMMENT '疾病实体短语',
    icd11_level1_code VARCHAR(80),
    icd11_level1_name VARCHAR(220) NOT NULL,
    icd11_level2_code VARCHAR(80),
    icd11_level2_name VARCHAR(220) NOT NULL,
    icd11_level3_code VARCHAR(80),
    icd11_level3_name VARCHAR(220),
    mapping_level VARCHAR(80),
    match_type VARCHAR(180),
    review_status VARCHAR(120),
    note TEXT,
    biomarker_cas VARCHAR(80),
    literature_count DECIMAL(18,4) NOT NULL DEFAULT 1 COMMENT '桑基图权重：涉及文献数',
    data_row_count BIGINT NOT NULL DEFAULT 0 COMMENT '后台统计：数据行数',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_icd11_sankey_category (target_category),
    KEY idx_icd11_sankey_level1 (target_category, icd11_level1_name),
    KEY idx_icd11_sankey_level2 (target_category, icd11_level2_name),
    KEY idx_icd11_sankey_drug (target_category, drug_name),
    KEY idx_icd11_sankey_biomarker (target_category, biomarker_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ICD11 四层桑基图聚合路径表';
